### ISSUE TITLE
Big endian platform not detected by farmhash

### ISSUE THREAD

**Issue by Nayana-ibm** [google/farmhash#10]
We are building TensorFlow on big endian system and farmhash is being downloaded as external dependency. 

Few tests are failing on our system ( s390x platform) as it's not getting detected as big endian by farmhash. We tried setting the macro FARMHASH_BIG_ENDIAN for s390x in farmhash.cc file  and with this change the tests are passing .

The farmhash/README mentions a known issue for big endian that
 `to make FarmHash work properly on big-endian platforms you may need to modify the wrapper .h file. `

Is farmhash.cc  right place to add a macro for our platform?
(We have seen macros used in config.h for big endian but doesn't seem to work for s390x )

**Comment by geoffpike** [comment]
In general, the tests are extremely unlikely to pass due to luck, so if you have a change that makes the tests pass then it should be safe to use.

If you don't want to modify the code, you might try compiling with WORDS_BIGENDIAN defined (e.g., g++ -DWORDS_BIGENDIAN). Or FARMHASH_BIG_ENDIAN.

**Comment by CDLuminate** [comment]
Is the `WORDS_BIGENDIAN` workaround robust enough for distribution? I'm about to fix the farmhash build failure for Debian. As reported here: https://github.com/google/farmhash/issues/12

**Comment by CDLuminate** [comment]
How about this patch?
```patch
diff --git a/src/farmhash.h b/src/farmhash.h
index d041488..52be397 100644
--- a/src/farmhash.h
+++ b/src/farmhash.h
@@ -292,4 +292,27 @@ inline uint128_t Fingerprint128(const Str& s) {
 
 }  // namespace NAMESPACE_FOR_HASH_FUNCTIONS
 
+// Detect big-endian architectures and inject FARMHASH_BIG_ENDIAN flag.
+#if defined (__mips__)
+  #if defined (__MIPSEB__)
+    #define FARMHASH_BIG_ENDIAN 
+  #elif defined (__MIPSEL__)
+  #else
+    #error MIPS no endian specified
+  #endif
+#elif defined (__s390__) || defined (__s390x__)
+  #define FARMHASH_BIG_ENDIAN 
+#elif defined (__powerpc__) || defined(__powerpc64__)
+  #if defined (__LITTLE_ENDIAN__)
+  #else
+    #define FARMHASH_BIG_ENDIAN 
+  #endif
+#elif defined (__hppa__)
+  #define FARMHASH_BIG_ENDIAN 
+#elif defined (__sparc__)
+  #define FARMHASH_BIG_ENDIAN 
+#elif defined (__alpha__)
+  #define FARMHASH_BIG_ENDIAN 
+#endif // end detect big-endian archs
+
 #endif  // FARM_HASH_H_
```

@geoffpike @Nayana-ibm

**Comment by Nayana-ibm** [comment]
@CDLuminate The patch looks good to me. 
Tests are passing on s390x platform with above code changes. 

Also, we had tried executing tests with --copt=-DWORDS_BIGENDIAN and it works too.

**Comment by CDLuminate** [comment]
@Nayana-ibm Thank you very much for the confirmation.

**Comment by Nayana-ibm** [comment]
@CDLuminate Any idea by when this will be merged?

**Comment by CDLuminate** [comment]
@Nayana-ibm I'm currently asking several Debian Developers for review. If it looks good to them, I'll update the Debian package with this patch and create a PR.

**Comment by CDLuminate** [comment]
This patch should be better for linux:
```patch
diff --git a/src/farmhash.h b/src/farmhash.h
index d041488..1bfcc46 100644
--- a/src/farmhash.h
+++ b/src/farmhash.h
@@ -292,4 +292,24 @@ inline uint128_t Fingerprint128(const Str& s) {
 
 }  // namespace NAMESPACE_FOR_HASH_FUNCTIONS
 
+/* gently define FARMHASH_BIG_ENDIAN when detected big-endian machine */
+#if defined(__BIG_ENDIAN__)
+  #if !defined(FARMHASH_BIG_ENDIAN)
+    #define FARMHASH_BIG_ENDIAN
+  #endif
+#elif defined(__LITTLE_ENDIAN)
+  // nothing for little-endian
+#else
+  #include <endian.h> // libc6-dev, GLIBC
+  #if defined(__BYTE_ORDER) && (__BYTE_ORDER == __BIG_ENDIAN)
+    #if !defined(FARMHASH_BIG_ENDIAN)
+      #define FARMHASH_BIG_ENDIAN
+    #endif
+  #elif defined(__BYTE_ORDER) && (__BYTE_ORDER == __LITTLE_ENDIAN)
+    // nothing for little-endian
+  #else
+    #error "Unable to determine endianness!"
+  #endif /* __BYTE_ORDER__ */
+#endif /* __BIG_ENDIAN__ */
+
 #endif  // FARM_HASH_H_

```

**Comment by CDLuminate** [comment]
The above patch doesn't consider the case of BSD.

This link is useful: http://esr.ibiblio.org/?p=5095

**Comment by Nayana-ibm** [comment]
@CDLuminate  Is this patch is reviewed? Any idea by when this will be merged?

**Comment by CDLuminate** [comment]
@Nayana-ibm The patch is already used in the Debian package[1], but it failed on s390x.
Actually that patch fixed only the powerpc and ppc64 build. see [2].

[1] https://tracker.debian.org/pkg/farmhash
[2] https://buildd.debian.org/status/logs.php?pkg=farmhash&suite=experimental
