### ISSUE TITLE
The initial Debian package of farmhash FTBFS on several architectures

### ISSUE THREAD

**Issue by CDLuminate** [google/farmhash#12]
All buildlogs can be found here:
https://buildd.debian.org/status/package.php?p=farmhash&suite=experimental

Farmhash failed to build on s390x and mips etc.

**Comment by CDLuminate** [comment]
The newest commit was successfully built on all architectures that Debian supports.

https://buildd.debian.org/status/package.php?p=farmhash

**Comment by geoffpike** [comment]
Thanks!
