### ISSUE TITLE
S390x support in farmhash 

### ISSUE THREAD

**Issue by Nayana-ibm** [google/farmhash#21]
We had raised an [issue](https://github.com/google/farmhash/commit/c56aabf8533e8c4952fb0318016f416edc2d376a) in google/farmhash master earlier for big endian. However due to restructuring in the code via latest commits, the support for s390x needs to be explicitly added.
`
filename: farmhash/src/farmhash.h`
```
#endif
- #elif defined(__OpenBSD__) || defined(__NetBSD__) || defined(__FreeBSD__) || defined(__DragonFly__) 
+ #elif defined(__OpenBSD__) || defined(__NetBSD__) || defined(__FreeBSD__) || defined(__DragonFly__) || defined(__s390x__)
 #include <sys/endian.h>
```

**Comment by geoffpike** [comment]
Fixed. Thanks!
