### ISSUE TITLE
make -j4 all check" fails

### ISSUE THREAD

**Issue by yasushi-saito** [google/farmhash#4]
It looks like farm-test rule runs twice, concurrently. "make all check", "make -j4 all", "make -j4 check" all succeeds. Only "make -j4 all check" fails.

Below is a log:

make  all-recursive
Making check in src
make[1]: Entering directory `/home/saito/src_master/__build__/third_party/farmha
sh-1.1.0/__tmp__/farmhash-1.1.0'
Making all in src
make[1]: Entering directory `/home/saito/src_master/__build__/third_party/farmha
sh-1.1.0/__tmp__/farmhash-1.1.0/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..   
  -g -msse4.2 -maes -O3 -MT farmhash.lo -MD -MP -MF .deps/farmhash.Tpo -c -o far
mhash.lo farmhash.cc
g++ -DHAVE_CONFIG_H -I. -I..     -g -msse4.2 -maes -O3 -MT farm-test.o -MD -MP -
MF .deps/farm-test.Tpo -c -o farm-test.o farm-test.cc
make[2]: Entering directory `/home/saito/src_master/__build__/third_party/farmha
sh-1.1.0/__tmp__/farmhash-1.1.0/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..   
  -g -msse4.2 -maes -O3 -MT farmhash.lo -MD -MP -MF .deps/farmhash.Tpo -c -o far
mhash.lo farmhash.cc
g++ -DHAVE_CONFIG_H -I. -I..     -g -msse4.2 -maes -O3 -MT farm-test.o -MD -MP -
MF .deps/farm-test.Tpo -c -o farm-test.o farm-test.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -g -msse4.2 -maes -O3 -MT farmha
sh.lo -MD -MP -MF .deps/farmhash.Tpo -c farmhash.cc  -fPIC -DPIC -o .libs/farmha
sh.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -g -msse4.2 -maes -O3 -MT farmha
sh.lo -MD -MP -MF .deps/farmhash.Tpo -c farmhash.cc  -fPIC -DPIC -o .libs/farmha
sh.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -g -msse4.2 -maes -O3 -MT farmha
sh.lo -MD -MP -MF .deps/farmhash.Tpo -c farmhash.cc -o farmhash.o >/dev/null 2>&
1
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -g -msse4.2 -maes -O3 -MT farmha
sh.lo -MD -MP -MF .deps/farmhash.Tpo -c farmhash.cc -o farmhash.o >/dev/null 2>&
1
mv -f .deps/farm-test.Tpo .deps/farm-test.Po
mv -f .deps/farm-test.Tpo .deps/farm-test.Po
mv: cannot stat ‘.deps/farm-test.Tpo’: No such file or directory
make[2]: *** [farm-test.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/farmhash.Tpo .deps/farmhash.Plo
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -msse4.2 -maes -O3   -o li
bfarmhash.la -rpath /home/saito/src_master/__build__/third_party/farmhash-1.1.0/
lib farmhash.lo  
mv -f .deps/farmhash.Tpo .deps/farmhash.Plo
mv: cannot stat ‘.deps/farmhash.Tpo’: No such file or directory
make[2]: *** [farmhash.lo] Error 1
make[2]: Leaving directory `/home/saito/src_master/__build__/third_party/farmhash-1.1.0/__tmp__/farmhash-1.1.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/saito/src_master/__build__/third_party/farmhash-1.1.0/__tmp__/farmhash-1.1.0'
make: *** [all] Error 2
make: *** Waiting for unfinished jobs....

**Comment by geoffpike** [comment]
Issues #4 and #5 are the same. Closing this one.
